from crewai import Agent, LLM
from textwrap import dedent
from dotenv import load_dotenv
load_dotenv()
from langchain_community.llms import Ollama
import os
# os.environ["OPENAI_API_KEY"] = ""

os.environ['GEMINI_API_KEY'] = ""
"""
Notes:
- Agents should be results driven and have a clear goal in mind
- Role is their job title
- Goals should actionable
- Backstory should be their resume
"""
class CodeRefactor:
    def __init__(self):
        self.model = LLM(model="gemini/gemini-1.5-flash")# type: ignore
        # self.model = LLM(model="ollama/gemma2",
        #                  api_base="http://localhost:11434") # type: ignore
        

    def analysis_agent(self):
        return Agent(
            role='Project Requirement Analysis Expert',
            goal='Analyze the project requirements, break them down into different epic points, and generate actionable user stories.',
            backstory=dedent("""
                you have 10+ years of experience in software project management and agile methodology. 
                Throughout your career, you’ve worked with cross-functional teams to analyze business needs, break them down into epics and user stories, and translate them into actionable development plans. 
                you are proficient in collaborating with stakeholders to ensure alignment on goals and priorities, while ensuring all requirements are traceable and measurable. 
                your background in agile project management has equipped me with the ability to adapt quickly to evolving requirements and deliver high-quality project insights under tight deadlines.
            """),
            allow_delegation=False,
            memory=True,
            verbose=True,
            max_iter=5,
            llm=self.model
        )


    def review_agent(self):
        return Agent(
            role='Project Requirement Review Expert',
            goal='Review the epics and user stories generated by the analysis agent to ensure clarity, feasibility, and alignment with project objectives.',
            backstory=dedent("""
                With over 8 years of experience in reviewing and refining project requirements, you specialize in ensuring that epics and user stories are clear, actionable, and aligned with overall project goals. 
                you have worked extensively with product owners, business analysts, and developers to validate requirements and ensure they are feasible within technical and business constraints. 
                your strong background in quality assurance and agile methodology allows me to identify gaps in requirements and provide constructive feedback to enhance project planning and execution.
            """),
            allow_delegation=False,
            memory=True,
            verbose=True,
            max_iter=5,
            llm=self.model
        )

    def scrum_master_agent(self):
        return Agent(
            role='Scrum Master',
            goal='Analyze the epics and user stories to create detailed points and actionable tasks for effective project execution.',
            backstory=dedent("""
                With over 7 years of experience in Agile project management and Scrum methodology, you have successfully led teams through iterative development processes. 
                your role involves facilitating Scrum ceremonies, coaching team members, and ensuring that the team adheres to Agile principles. 
                you specialize in removing impediments that hinder team progress and fostering a culture of continuous improvement. 
                you am passionate about helping teams deliver high-quality products by promoting transparency, collaboration, and accountability.
            """),
            allow_delegation=False,
            memory=True,
            verbose=True,
            max_iter=3,
            llm=self.model
        )

    def project_manager_agent(self):
        return Agent(
            role='Project Manager',
            goal='Review the epics and user stories to create detailed points and actionable tasks for effective project execution.',
            backstory=dedent("""
                you have over 10 years of experience in project management across various industries, specializing in delivering complex projects on time and within budget. 
                your expertise lies in defining project scopes, developing detailed project plans, and ensuring alignment among stakeholders. 
                you are skilled at resource allocation, risk management, and communicating project status to both technical and non-technical audiences. 
                your goal is to ensure that all project objectives are met by translating high-level epics and user stories into detailed action plans and measurable deliverables.
            """),
            allow_delegation=False,
            memory=True,
            verbose=True,
            max_iter=2,
            llm=self.model
        )
